# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nksVTshabo5Pm518HG9wqkgu4VGSYmVw

Importing pandas
"""

import pandas as pd

"""Reading the input csv files"""

user_data = pd.read_csv('userid_input1.csv')
statements_data=pd.read_csv('rigorbuilder_input2.csv')

"""Merging the datasets"""

merge_tables = pd.merge(user_data, statements_data, left_on='User ID', right_on='uid')
leaderboad_1 = merge_tables.groupby('Team Name').agg({'total_statements': 'mean', 'total_reasons': 'mean'}).reset_index()

"""Assigning ranks

"""

leaderboad_1['Ranks'] = leaderboad_1.apply(lambda x: (x['total_statements'], -x['total_reasons']), axis=1).rank(method='dense', ascending=False).astype(int)
leaderboad_1 = leaderboad_1[['Ranks', 'Team Name', 'total_statements', 'total_reasons']]
leaderboad_1= leaderboad_1.rename(columns={'Team Name':'Thinking Team names','total_statements': 'Average Statements', 'total_reasons': 'Average Reasons'})
leaderboad_1 = leaderboad_1.round(2)
Team_leaderboad = leaderboad_1.sort_values(['Average Statements', 'Average Reasons'], ascending=False).reset_index(drop=True)

"""printing Team leaderboad

"""

print(Team_leaderboad)

"""creating individual leaderboard"""

user_satatements= pd.read_csv('rigorbuilder_input2.csv') 
user_satatements['Total'] = user_satatements['total_statements'] + user_satatements['total_reasons'] 
user_satatements= user_satatements.sort_values(['Total', 'name'], ascending=[False, True]) 
user_satatements['Rank'] = user_satatements.reset_index().index + 1 
individual = user_satatements[['Rank', 'name', 'uid', 'total_statements', 'total_reasons']] 
individual.columns = ['Rank', 'Name', 'UID', 'No. of Statements', 'No. of Reasons'] 
individual_leaderboard = individual.to_string(index=False)

"""Printing Individual leaderboard

"""

print(individual_leaderboard)